apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
      app: category-service
    name: category-service
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
  labels:
    app: category
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: category
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
      app: category-service
    name: category-service:view
roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: view
subjects:
    - kind: ServiceAccount
      name: category-service
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: category-service
spec:
  selector:
    matchLabels:
      app: category
  replicas: 1
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
      - name: category
        image: swadharma/category-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PROFILES
          value: kubernetes
        - name: PORT
          value: "8081"
        - name: DBURL
          valueFrom:
            secretKeyRef:
              name: database
              key: dburl
        - name: DBUSERNAME
          valueFrom:
            secretKeyRef:
              name: database
              key: dbusername
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: dbpassword
        ports:
        - containerPort: 8081
          name: category
